# Generated by Django 5.1.2 on 2024-11-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(default='User', max_length=10),
            preserve_default=False,
        ),
    ]
