# Generated by Django 5.1.2 on 2024-11-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_name_user_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
